---
dvwa_db_name: "dvwadb"
dvwa_db_user: "dvwauser"
dvwa_db_password: "dvwapassword"
dvwa_name: "dvwa"
dvwa_directory: "/var/www/html/{{ dvwa_name }}"
dvwa_sources: "https://github.com/digininja/DVWA.git"
dvwa_user: "dvwa"
dvwa_server_admin: "joshua.jourdam@reseau.eseo.fr"
dvwa_error_log_file: "{{ dvwa_name }}-error.log"
dvwa_access_log_file: "{{ dvwa_name }}-access.log"