---
- name: Install MariaDB
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: present

- name: Start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
