---
- name: "Install docker dependencies"
  ansible.builtin.apt:
    name: 
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: "present"

- name: "Add docker repository"
  ansible.builtin.shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "Install docker"
  ansible.builtin.apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    update_cache: true
    state: "present"

- name: "Run webgoat container"
  ansible.builtin.shell: |
    docker run -it -p 192.168.56.44:8080:8080 -p 192.168.56.44:9090:9090 -e TZ=Europe/Paris webgoat/webgoat &
