Vagrant.require_version ">= 1.8.0"
Vagrant.configure("2") do |config|
  config.vm.box = "chavinje/fr-bull-64"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--groups", "/Ansible"]
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end

  config.vm.provision "global", type:'ansible' do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provisioning/global.yml"
    ansible.groups = {
      "global" => ["victim", "firewall", "attack"]
    }
  end

  config.vm.define "firewall" do |machine|
    machine.vm.hostname = "firewall"
    machine.vm.network :private_network, ip: "192.168.56.11"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "firewall"]
    end
  end

  config.vm.define "attack" do |machine|
    machine.vm.hostname = "attack"
    machine.vm.network :private_network, ip: "192.168.56.33"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "attack"]
    end
  end

  config.vm.define "victim" do |machine|
    machine.vm.hostname = "victim"
    machine.vm.network :private_network, ip: "192.168.56.22"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "victim"]
    end
    config.vm.provision "dvwa", type:'ansible' do |ansible|
      ansible.playbook = "provisioning/dvwa.yml"
      ansible.groups = {
        "apache" => ["victim"],
        "mariadb" => ["victim"],
        "dvwa" => ["victim"]
      }
    end

    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      sleep 3
      service ssh restart
      SHELL
  end
end
