---
# tasks file for apache
- name: "Install Apache"
  ansible.builtin.apt:
    name: apache2
    state: "present"

- name: "Apache service activation"
  ansible.builtin.service:
    name: "apache2"
    state: "started"
    enabled: true

- name: "Install php"
  ansible.builtin.include_tasks: "php-install.yml"
  when: "php_install|default(False)|bool"
